# Generated by Django 5.0.4 on 2024-05-12 06:31

from django.db import migrations

def create_tipousuario(apps, _):
    TipoUsuario = apps.get_model('core', 'TipoUsuario')
    TipoUsuario.objects.create(nom_tipo='comun')
    TipoUsuario.objects.create(nom_tipo='miembro')
    TipoUsuario.objects.create(nom_tipo='admin')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_tipousuario),
    ]
