# Generated by Django 5.0.4 on 2024-05-13 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usuario_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudp',
            name='artista_producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.artista'),
        ),
    ]
