# Generated by Django 5.0.4 on 2024-05-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
