# Generated by Django 5.0.6 on 2024-06-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_historial_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_compra',
            name='total_clp',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='historial_compra',
            name='total_usd',
            field=models.CharField(),
        ),
    ]
