# Generated by Django 5.0.6 on 2024-06-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_historial_compra_total_clp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_compra',
            name='cantidades_productos',
            field=models.JSONField(default=dict),
        ),
    ]
