# Generated by Django 5.0.6 on 2024-06-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_historial_compra_cantidades_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_compra',
            name='total_clp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='historial_compra',
            name='total_usd',
            field=models.CharField(max_length=10),
        ),
    ]
